apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-pvc-many
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 